CREATE TABLE INTEGRATION_ADAPTER (
    INTEGRATION_ADAPTER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME                   VARCHAR(100)                   NOT NULL,
    TYPE                   VARCHAR(500)                   NOT NULL,
    STATUS                VARCHAR(15)                    NOT NULL,
    CRTE_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDT_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    UPDATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    DELETE_IND            NUMBER(1, 0) DEFAULT 0         NOT NULL,
    UPDT_SEQ_NUM          NUMBER DEFAULT 1               NOT NULL,
    PRIMARY KEY (INTEGRATION_ADAPTER_ID)
);

CREATE TABLE INTEGRATION_CLIENT_INVENTORY (
    INTEGRATION_CLIENT_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME                  VARCHAR(100)                   NOT NULL,
    DESCRIPTION           VARCHAR(500)                   NOT NULL,
    CUSTOMER_CODE         VARCHAR(50)                    NOT NULL,
    ORG_ID                VARCHAR(50)                    NOT NULL,
    INBOUND_ADAPTER_ID    INTEGER                    NOT NULL,
    OUTBOUND_ADAPTER_ID   INTEGER                    NOT NULL,
    STATUS                VARCHAR(15)                    NOT NULL,
    CRTE_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDT_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    UPDATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    DELETE_IND            NUMBER(1, 0) DEFAULT 0         NOT NULL,
    UPDT_SEQ_NUM          NUMBER DEFAULT 1               NOT NULL,
    PRIMARY KEY (INTEGRATION_CLIENT_ID) ,
    CONSTRAINT FK_ICLIENT_INBOUND_TO_ICLIENT_ADAPTER FOREIGN KEY (INBOUND_ADAPTER_ID)
    REFERENCES INTEGRATION_ADAPTER (INTEGRATION_ADAPTER_ID),
    CONSTRAINT FK_ICLIENT_OUTBOUND_TO_ICLIENT_ADAPTER FOREIGN KEY (OUTBOUND_ADAPTER_ID)
    REFERENCES INTEGRATION_ADAPTER (INTEGRATION_ADAPTER_ID)
);

CREATE TABLE INTEGRATION_CLIENT_CONFIG (
    INTEGRATION_CLIENT_CONFIG_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    INTEGRATION_CLIENT_ID INTEGER                    NOT NULL,
    NAME                  VARCHAR(100)                   NOT NULL,
    DESCRIPTION           VARCHAR(500)                   NOT NULL,
    STATUS                VARCHAR(15)                    NOT NULL,
    CRTE_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDT_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    UPDATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    DELETE_IND            NUMBER(1, 0) DEFAULT 0         NOT NULL,
    UPDT_SEQ_NUM          NUMBER DEFAULT 1               NOT NULL,
    PRIMARY KEY (INTEGRATION_CLIENT_CONFIG_ID),
    CONSTRAINT FK_ICLIENT_CONFIG_TO_ICLIENT_INV FOREIGN KEY (INTEGRATION_CLIENT_ID)
    REFERENCES INTEGRATION_CLIENT_INVENTORY (INTEGRATION_CLIENT_ID)
);

CREATE TABLE INTEGRATION_CLIENT_STATUS (
    INTEGRATION_CLIENT_STATUS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    INTEGRATION_CLIENT_ID        INTEGER                    NOT NULL,
    HEALTH_STATUS                VARCHAR(50)                    NOT NULL,
    HEALTH_STATUS_DESCRIPTION    VARCHAR(500)                   NOT NULL,
    CRTE_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDT_SRC_ID           VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    UPDATED_BY            VARCHAR2(50) DEFAULT 'Default' NOT NULL,
    CREATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    UPDATED_DATE          DATE DEFAULT sysdate           NOT NULL,
    DELETE_IND            NUMBER(1, 0) DEFAULT 0         NOT NULL,
    UPDT_SEQ_NUM          NUMBER DEFAULT 1               NOT NULL,
    PRIMARY KEY (INTEGRATION_CLIENT_STATUS_ID) ,
    CONSTRAINT FK_ICLIENT_STATUS_TO_ICLIENT_INV FOREIGN KEY (INTEGRATION_CLIENT_ID)
    REFERENCES INTEGRATION_CLIENT_INVENTORY (INTEGRATION_CLIENT_ID)
);